name: Mac和Windows打包

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "v20.16.0"

      - name: 安装依赖
        run: npm install

      - name: Win打包
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Mac打包
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Win查看打包后的文件结构
        if: matrix.os == 'windows-latest'
        run: |
              echo "打包后的文件结构如下:"
              dir dist

      - name: Mac查看打包后的文件结构
        if: matrix.os == 'macos-latest'
        run: |
              echo "打包后的文件结构如下:"
              ls -R ./dist

      - name: Win压缩 dist 目录
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path ./dist/* -DestinationPath Win_Release.zip

      - name: Mac压缩 dist 目录
        if: matrix.os == 'macos-latest'
        run: |
          zip -r Mac_Release.zip ./dist
        shell: bash

  release:
    runs-on: macos-latest
    needs: build
    steps:
      - name: 创建 GitHub Release 并上传文件
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Win_Release.zip
            Mac_Release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
