name: Build and release Electron apps

# on:
#   push:
#     tags:
#       - v[0-9]+.[0-9]+.[0-9]+

on:
  push:
    branches:
      - main  # 根据需要更改分支

jobs:
  build-and-release:
    name: Build and release by tag
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ windows-latest, macos-latest]
    
    permissions:
      contents: write

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: 安装依赖
        run: npm install

      # Windows平台执行命令
      - name: Build electron apps for Windows platform
        if: matrix.os == 'windows-latest'
        run: |
          npm run build:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # macOS平台执行命令
      - name: Build electron apps for macOS platform
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts after build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ matrix.os }}-build
          path: release

      # 创建 GitHub Release
      - name: Release
        uses: softprops/action-gh-release@v2.0.4
      # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "release/**"
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
