name: Mac和Windows打包

on:
    push:
      branches:
        - main  # 根据需要更改分支

jobs:
    build: # 作业名称
        runs-on: ${{ matrix.os }} # 运行环境

        strategy:
            matrix:
                os: [macos-latest, windows-latest] # 运行环境

        steps:
            - name: 检出代码
              uses: actions/checkout@v4 # 检出代码

            - name: 安装Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "v20.16.0" # 设置Node.js版本

            - name: 安装依赖
              run: npm install

            - name: Win打包
              if: matrix.os == 'windows-latest'
              run: npm run build:win

            - name: Mac打包
              if: matrix.os == 'macos-latest'
              run: npm run build:mac
              
            - name: Win查看打包后的文件结构
              if: matrix.os == 'windows-latest'
              run: |
                    echo "打包后的文件结构如下:"
                    dir dist

            - name: Mac查看打包后的文件结构
              if: matrix.os == 'macos-latest'
              run: |
                    echo "打包后的文件结构如下:"
                    ls -R ./dist
              
            - name: Win压缩 dist 目录
              if: matrix.os == 'windows-latest'
              run: |
                Compress-Archive -Path ./dist/* -DestinationPath Win_Release.zip

            - name: Mac压缩 dist 目录
              if: matrix.os == 'macos-latest'
              run: |
                zip -r Mac_Release.zip ./dist
              shell: bash

            - name: 上传 Win 版本为 artifact
              if: matrix.os == 'windows-latest'
              uses: actions/upload-artifact@v3
              with:
                name: Win_Release
                path: ./Win_Release.zip

            - name: 上传 Mac 版本为 artifact
              if: matrix.os == 'macos-latest'
              uses: actions/upload-artifact@v3
              with:
                name: Mac_Release
                path: ./Mac_Release.zip

    release:
        runs-on: ubuntu-latest
        needs: build  # 等待build job完成
        steps:
            - name: 检出代码
              uses: actions/checkout@v4

            - name: 下载 Windows 打包 artifact
              uses: actions/download-artifact@v3
              with:
                name: Win_Release
                path: ./release-assets

            - name: 下载 Mac 打包 artifact
              uses: actions/download-artifact@v3
              with:
                name: Mac_Release
                path: ./release-assets

            - name: 创建 GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v1.0.${{ github.run_number }}
                release_name: 'Release v1.0.${{ github.run_number }}'
                draft: false
                prerelease: false

            - name: 上传 Win 版本到 GitHub Release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./release-assets/Win_Release.zip
                asset_name: yuelan_Win.zip
                asset_content_type: application/zip

            - name: 上传 Mac 版本到 GitHub Release
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./release-assets/Mac_Release.zip
                asset_name: yuelan_Mac.zip
                asset_content_type: application/zip
